// Shared product data for merch catalog - no database dependency

export const BRANDS = [
  { id: "gildan", name: "Gildan", slug: "gildan", logo: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=100&h=50&fit=crop" },
  { id: "next-level", name: "Next Level", slug: "next-level", logo: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=100&h=50&fit=crop" },
  { id: "bella-canvas", name: "BELLA+CANVAS", slug: "bella-canvas", logo: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=100&h=50&fit=crop" },
  { id: "american-apparel", name: "American Apparel", slug: "american-apparel", logo: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=100&h=50&fit=crop" },
]

export const CATEGORIES = [
  { id: "crew-neck-tees", name: "Crew Neck T-Shirts", slug: "crew-neck-tees" },
  { id: "v-neck-tees", name: "V-Neck T-Shirts", slug: "v-neck-tees" },
  { id: "long-sleeve-tees", name: "Long Sleeve T-Shirts", slug: "long-sleeve-tees" },
  { id: "hoodies", name: "Hoodies", slug: "hoodies" },
  { id: "sweatshirts", name: "Crew Neck Sweatshirts", slug: "sweatshirts" },
  { id: "polos", name: "Polos", slug: "polos" },
]

export const PRINT_METHODS = [
  { id: "silkscreen", name: "Screen Printing", slug: "silkscreen", min_quantity: 24, best_for: "Best for 1-6 color designs on bulk orders", pricing_note: "From $0.33/piece at high volumes" },
  { id: "embroidery", name: "Embroidery", slug: "embroidery", min_quantity: 6, best_for: "Premium stitched logos for corporate & professional wear", pricing_note: "From $2.30/piece for simple designs" },
  { id: "dtf", name: "DTF Printing", slug: "dtf", min_quantity: 1, best_for: "Full-color prints, photos, unlimited colors - no minimums", pricing_note: "From $5.45/piece for small prints" },
]

export interface MerchProduct {
  id: string
  style_number: string
  name: string
  description: string
  fabric: string
  weight: string
  sizes: string[]
  colors: { name: string; hex: string }[]
  base_price: number
  msrp: number
  print_methods: string[]
  brand: typeof BRANDS[0]
  category: typeof CATEGORIES[0]
  image: string
  badge?: "Best Seller" | "Staff Pick" | "Top Rated" | "New"
  rating: number
  reviews: string
}

// Color palette based on actual Gildan/Next Level/BELLA+CANVAS colors
const STANDARD_COLORS = [
  { name: "Black", hex: "#1a1a1a" },
  { name: "White", hex: "#ffffff" },
  { name: "Navy", hex: "#1e3a5f" },
  { name: "Royal Blue", hex: "#2563eb" },
  { name: "Heather Grey", hex: "#9ca3af" },
  { name: "Charcoal", hex: "#374151" },
  { name: "Red", hex: "#dc2626" },
  { name: "Cardinal", hex: "#991b1b" },
  { name: "Forest Green", hex: "#166534" },
  { name: "Kelly Green", hex: "#16a34a" },
  { name: "Gold", hex: "#ca8a04" },
  { name: "Orange", hex: "#ea580c" },
  { name: "Purple", hex: "#7c3aed" },
  { name: "Maroon", hex: "#7f1d1d" },
  { name: "Light Blue", hex: "#7dd3fc" },
  { name: "Pink", hex: "#f472b6" },
  { name: "Sand", hex: "#d4b896" },
  { name: "Olive", hex: "#65a30d" },
]

const PREMIUM_COLORS = [
  ...STANDARD_COLORS,
  { name: "Vintage Navy", hex: "#2d3748" },
  { name: "Heather Mint", hex: "#a7f3d0" },
  { name: "Dusty Rose", hex: "#e8b4b8" },
  { name: "Sunset Orange", hex: "#fb923c" },
  { name: "Mauve", hex: "#c084fc" },
  { name: "Sage", hex: "#86efac" },
  { name: "Mustard", hex: "#fbbf24" },
  { name: "Slate", hex: "#64748b" },
  { name: "Coral", hex: "#f87171" },
  { name: "Teal", hex: "#14b8a6" },
]

export const MERCH_PRODUCTS: MerchProduct[] = [
  // ===== GILDAN PRODUCTS =====
  {
    id: "g-5000",
    style_number: "5000",
    name: "Heavy Cotton Tee",
    description: "Classic heavyweight t-shirt for everyday wear. Preshrunk 100% cotton for durability.",
    fabric: "100% Cotton",
    weight: "5.3 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: STANDARD_COLORS.slice(0, 18),
    base_price: 2.74,
    msrp: 9.90,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=600&fit=crop",
    badge: "Best Seller",
    rating: 4.5,
    reviews: "10,000+",
  },
  {
    id: "g-64000",
    style_number: "64000",
    name: "Softstyle Tee",
    description: "Soft, fashion-forward tee with a modern fit. Ring-spun cotton for superior comfort.",
    fabric: "100% Ring-Spun Cotton",
    weight: "4.5 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: PREMIUM_COLORS,
    base_price: 3.07,
    msrp: 11.65,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=600&h=600&fit=crop",
    badge: "Staff Pick",
    rating: 4.7,
    reviews: "8,500+",
  },
  {
    id: "g-3000",
    style_number: "3000",
    name: "Ultra Cotton Tee",
    description: "Heavy-duty cotton for maximum durability. Perfect for workwear and uniforms.",
    fabric: "100% Cotton",
    weight: "6.0 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: STANDARD_COLORS.slice(0, 15),
    base_price: 2.27,
    msrp: 8.50,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=600&fit=crop",
    rating: 4.4,
    reviews: "5,200+",
  },
  {
    id: "g-2300",
    style_number: "2300",
    name: "Softstyle V-Neck Tee",
    description: "Soft V-neck for a modern, stylish look. Perfect for casual and business casual.",
    fabric: "100% Ring-Spun Cotton",
    weight: "4.5 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: STANDARD_COLORS.slice(0, 12),
    base_price: 5.07,
    msrp: 14.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[1],
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=600&fit=crop",
    rating: 4.3,
    reviews: "3,100+",
  },
  {
    id: "g-2400",
    style_number: "2400",
    name: "Ultra Cotton Long Sleeve Tee",
    description: "Heavyweight long sleeve t-shirt for durability. Perfect for layering or cool weather.",
    fabric: "100% Cotton",
    weight: "6.0 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: STANDARD_COLORS.slice(0, 14),
    base_price: 5.05,
    msrp: 15.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[2],
    image: "https://images.unsplash.com/photo-1618354691438-25bc04584c23?w=600&h=600&fit=crop",
    rating: 4.4,
    reviews: "2,800+",
  },
  {
    id: "g-5300",
    style_number: "5300",
    name: "Heavy Cotton Long Sleeve",
    description: "Classic long sleeve for all seasons. Same quality as the 5000 with extended coverage.",
    fabric: "100% Cotton",
    weight: "5.3 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: STANDARD_COLORS.slice(0, 14),
    base_price: 4.02,
    msrp: 12.50,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[2],
    image: "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=600&h=600&fit=crop",
    rating: 4.5,
    reviews: "4,800+",
  },
  {
    id: "g-64400",
    style_number: "64400",
    name: "Softstyle Long Sleeve Tee",
    description: "Soft ringspun cotton long sleeve for maximum comfort. Modern retail fit.",
    fabric: "100% Ring Spun Cotton",
    weight: "4.5 oz",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: STANDARD_COLORS.slice(0, 12),
    base_price: 4.95,
    msrp: 14.50,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[2],
    image: "https://images.unsplash.com/photo-1618354691551-44de113f0164?w=600&h=600&fit=crop",
    rating: 4.4,
    reviews: "2,100+",
  },
  {
    id: "g-18000",
    style_number: "18000",
    name: "Heavy Blend Pullover Hoodie",
    description: "Classic pullover hoodie with front pouch pocket. Air jet yarn for softer feel.",
    fabric: "50/50 Cotton-Poly",
    weight: "8.0 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: STANDARD_COLORS.slice(0, 16),
    base_price: 7.09,
    msrp: 24.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[3],
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=600&fit=crop",
    badge: "Best Seller",
    rating: 4.6,
    reviews: "12,000+",
  },
  {
    id: "g-18600",
    style_number: "18600",
    name: "Heavy Blend Full Zip Hoodie",
    description: "Full zip hoodie for versatility. Perfect for layering.",
    fabric: "50/50 Cotton-Poly",
    weight: "8.0 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: STANDARD_COLORS.slice(0, 12),
    base_price: 18.13,
    msrp: 35.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[3],
    image: "https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&h=600&fit=crop",
    rating: 4.5,
    reviews: "3,200+",
  },
  {
    id: "g-18200",
    style_number: "18200",
    name: "Heavy Blend Crew Sweatshirt",
    description: "Classic crew neck sweatshirt. Soft fleece for comfort.",
    fabric: "50/50 Cotton-Poly",
    weight: "8.0 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: STANDARD_COLORS.slice(0, 14),
    base_price: 8.45,
    msrp: 22.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[4],
    image: "https://images.unsplash.com/photo-1572495641004-28421ae29ed4?w=600&h=600&fit=crop",
    rating: 4.4,
    reviews: "2,800+",
  },
  {
    id: "g-8800",
    style_number: "8800",
    name: "DryBlend Jersey Polo",
    description: "Moisture-wicking performance polo. Perfect for corporate uniforms.",
    fabric: "50/50 Cotton-Poly",
    weight: "5.6 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: STANDARD_COLORS.slice(0, 10),
    base_price: 7.33,
    msrp: 18.00,
    print_methods: ["silkscreen", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[5],
    image: "https://images.unsplash.com/photo-1625910513413-5fc5dc0c1a15?w=600&h=600&fit=crop",
    badge: "Top Rated",
    rating: 4.7,
    reviews: "6,500+",
  },
  {
    id: "g-sf000",
    style_number: "SF000",
    name: "Softstyle Fleece Crewneck",
    description: "Premium fleece crewneck with modern fit. Soft ring spun cotton blend.",
    fabric: "80% Ring Spun Cotton / 20% Polyester",
    weight: "7.2 oz",
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: STANDARD_COLORS.slice(0, 10),
    base_price: 9.30,
    msrp: 28.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[0],
    category: CATEGORIES[4],
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=600&fit=crop",
    rating: 4.5,
    reviews: "1,900+",
  },

  // ===== NEXT LEVEL PRODUCTS =====
  {
    id: "nl-3600",
    style_number: "3600",
    name: "Unisex Cotton T-Shirt",
    description: "Super soft premium cotton tee with modern fit. Side-seamed for quality.",
    fabric: "100% Combed Ring-Spun Cotton",
    weight: "4.3 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL", "6XL"],
    colors: PREMIUM_COLORS,
    base_price: 4.08,
    msrp: 12.75,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[1],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=600&h=600&fit=crop",
    badge: "Staff Pick",
    rating: 4.8,
    reviews: "9,200+",
  },
  {
    id: "nl-6210",
    style_number: "6210",
    name: "CVC Crew Tee",
    description: "Heathered blend for ultimate softness. Perfect drape and fit.",
    fabric: "60/40 Cotton-Poly CVC",
    weight: "4.3 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 15),
    base_price: 4.19,
    msrp: 13.50,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[1],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1529374255404-311a2a4f1fd9?w=600&h=600&fit=crop",
    rating: 4.6,
    reviews: "4,100+",
  },
  {
    id: "nl-9000",
    style_number: "9000",
    name: "Unisex Classic Pullover Hoodie",
    description: "Premium fleece hoodie with retail fit. Ring-spun cotton blend.",
    fabric: "80/20 Ring-Spun Cotton-Poly Fleece",
    weight: "8.0 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 12),
    base_price: 14.48,
    msrp: 38.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[1],
    category: CATEGORIES[3],
    image: "https://images.unsplash.com/photo-1509942774463-acf339cf87d5?w=600&h=600&fit=crop",
    badge: "Top Rated",
    rating: 4.8,
    reviews: "5,600+",
  },

  // ===== BELLA + CANVAS PRODUCTS =====
  {
    id: "bc-3001",
    style_number: "3001",
    name: "Unisex Jersey Tee",
    description: "The go-to premium blank. Side-seamed, retail fit with soft hand feel.",
    fabric: "100% Airlume Combed & Ring-Spun Cotton",
    weight: "4.2 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: PREMIUM_COLORS,
    base_price: 4.49,
    msrp: 15.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?w=600&h=600&fit=crop",
    badge: "Best Seller",
    rating: 4.9,
    reviews: "15,000+",
  },
  {
    id: "bc-3001cvc",
    style_number: "3001CVC",
    name: "CVC Unisex Jersey Tee",
    description: "Heathered CVC blend for extra softness. Same great fit as 3001.",
    fabric: "52/48 CVC Cotton-Poly Airlume",
    weight: "4.2 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"],
    colors: PREMIUM_COLORS.slice(0, 20),
    base_price: 4.59,
    msrp: 15.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=600&h=600&fit=crop",
    rating: 4.7,
    reviews: "7,300+",
  },
  {
    id: "bc-3413",
    style_number: "3413",
    name: "Unisex Triblend Tee",
    description: "Ultimate softness triblend. Vintage look with modern comfort.",
    fabric: "50/25/25 Poly-Cotton-Rayon Triblend",
    weight: "3.8 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    colors: PREMIUM_COLORS.slice(0, 18),
    base_price: 6.49,
    msrp: 18.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=600&h=600&fit=crop",
    badge: "Staff Pick",
    rating: 4.8,
    reviews: "6,800+",
  },
  {
    id: "bc-3005",
    style_number: "3005",
    name: "Unisex Jersey V-Neck Tee",
    description: "Fashion V-neck with the same quality as the 3001.",
    fabric: "100% Airlume Combed & Ring-Spun Cotton",
    weight: "4.2 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 15),
    base_price: 5.69,
    msrp: 16.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[1],
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&h=600&fit=crop",
    rating: 4.6,
    reviews: "3,400+",
  },
  {
    id: "bc-3501",
    style_number: "3501",
    name: "Unisex Jersey Long Sleeve Tee",
    description: "Long sleeve version of the iconic 3001. Same premium quality.",
    fabric: "100% Airlume Combed & Ring-Spun Cotton",
    weight: "4.2 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 16),
    base_price: 7.39,
    msrp: 20.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[2],
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=600&fit=crop",
    rating: 4.7,
    reviews: "4,200+",
  },
  {
    id: "bc-3719",
    style_number: "3719",
    name: "Unisex Sponge Fleece Pullover Hoodie",
    description: "Premium sponge fleece hoodie. Ultra-soft with retail quality.",
    fabric: "52/48 Airlume Cotton-Poly Sponge Fleece",
    weight: "7.5 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 20),
    base_price: 17.59,
    msrp: 45.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[3],
    image: "https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=600&h=600&fit=crop",
    badge: "Top Rated",
    rating: 4.9,
    reviews: "8,900+",
  },
  {
    id: "bc-3901",
    style_number: "3901",
    name: "Unisex Sponge Fleece Crew Sweatshirt",
    description: "Premium crew sweatshirt with sponge fleece interior.",
    fabric: "52/48 Airlume Cotton-Poly Sponge Fleece",
    weight: "7.5 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 14),
    base_price: 16.49,
    msrp: 40.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[2],
    category: CATEGORIES[4],
    image: "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600&h=600&fit=crop",
    rating: 4.7,
    reviews: "3,100+",
  },

  // ===== AMERICAN APPAREL PRODUCTS =====
  {
    id: "aa-2001",
    style_number: "2001",
    name: "Fine Jersey Tee",
    description: "Made in LA fine jersey. Classic American Apparel quality.",
    fabric: "100% Fine Jersey Cotton",
    weight: "4.3 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    colors: PREMIUM_COLORS.slice(0, 22),
    base_price: 4.68,
    msrp: 16.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[3],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1622445275576-721325763afe?w=600&h=600&fit=crop",
    badge: "New",
    rating: 4.6,
    reviews: "2,800+",
  },
  {
    id: "aa-2001cvc",
    style_number: "2001CVC",
    name: "CVC Fine Jersey Tee",
    description: "Heathered CVC blend with LA-made quality.",
    fabric: "60/40 CVC Cotton-Poly",
    weight: "4.3 oz",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 15),
    base_price: 4.68,
    msrp: 16.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[3],
    category: CATEGORIES[0],
    image: "https://images.unsplash.com/photo-1618354691551-44de113f0164?w=600&h=600&fit=crop",
    rating: 4.5,
    reviews: "1,900+",
  },
  {
    id: "aa-9001",
    style_number: "AA9001",
    name: "ReFlex Fleece Pullover Hoodie",
    description: "Sustainable fleece hoodie with modern fit.",
    fabric: "50/50 Fleece Cotton-Poly",
    weight: "8.0 oz",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    colors: PREMIUM_COLORS.slice(0, 12),
    base_price: 9.65,
    msrp: 32.00,
    print_methods: ["silkscreen", "dtf", "embroidery"],
    brand: BRANDS[3],
    category: CATEGORIES[3],
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=600&h=600&fit=crop",
    rating: 4.5,
    reviews: "1,400+",
  },
]

// Helper function to get products by category
export function getProductsByCategory(categorySlug: string): MerchProduct[] {
  return MERCH_PRODUCTS.filter(p => p.category.slug === categorySlug)
}

// Helper function to get products by brand
export function getProductsByBrand(brandSlug: string): MerchProduct[] {
  return MERCH_PRODUCTS.filter(p => p.brand.slug === brandSlug)
}

// Helper function to get featured/best seller products
export function getFeaturedProducts(): MerchProduct[] {
  return MERCH_PRODUCTS.filter(p => p.badge === "Best Seller" || p.badge === "Top Rated")
}
