-- Original, SEO-safe product descriptions authored in Web2Print USA's own voice.
-- Rewrites the earlier verbatim vendor copy (scripts 016/017) and fills every
-- remaining product-type slug. Generated by scripts/apply-descriptions.mjs.
-- Run in Supabase SQL Editor (or via the apply script).

INSERT INTO product_content (category_slug, description)
VALUES

('business-cards-standard',
 'Make a strong first impression with standard business cards built for everyday networking. Choose from a broad lineup of sizes, paper stocks, and finishes to match your brand, whether you prefer a clean matte look or a glossy, high-contrast finish. A dependable, budget-friendly staple for any professional.'),

('raised-foil',
 'Add a touch of luxury with raised foil business cards. Metallic foil accents sit slightly above the surface, catching the light and drawing the eye to your logo, name, and key details. A premium finish that makes your card feel as impressive as it looks.'),

('silk-cards',
 'Silk business cards are coated with a soft-touch silk laminate that gives them a smooth, velvety feel and a subtle sheen. The durable coating resists tears, water, and everyday wear, so your cards keep looking sharp long after you hand them out.'),

('suede-cards',
 'Suede business cards feature a soft, matte laminate with a plush, tactile finish that invites people to hold on to them. The luxe surface pairs beautifully with bold colors and can be enhanced further with spot gloss or foil accents.'),

('pearl-cards',
 'Pearl business cards are printed on shimmering metallic stock that gives your colors a soft, iridescent glow. The subtle pearlescent sheen adds depth and elegance, making them a memorable choice for photographers, designers, and premium brands.'),

('natural-cards',
 'Natural business cards are printed on uncoated, eco-friendly stock with a clean, organic feel. The untreated surface is easy to write on and gives your brand an authentic, understated look that stands apart from glossy alternatives.'),

('painted-edge-cards',
 'Painted edge business cards feature a thick, luxurious stock with a band of color painted along the edges. The bold color contrast and substantial weight create a high-end, unforgettable card that feels as premium as your brand.'),

('brown-kraft-cards',
 'Brown kraft business cards are printed on recycled kraft stock with a warm, natural brown tone. Their rustic, eco-conscious character is perfect for artisans, cafes, and brands that value a handmade, sustainable feel.'),

('akuafoil',
 'Akuafoil business cards use a multi-tonal foil process to create brilliant, rainbow-like metallic effects across your design. The eye-catching shimmer adds a high-end, artistic finish that is impossible to ignore.'),

('linen-uncoated',
 'Linen business cards are printed on textured, uncoated stock with a subtle woven pattern. The classic, refined surface adds tactile sophistication and stays easy to write on for notes and appointments.'),

('plastic-cards',
 'Plastic business cards are printed on durable, waterproof PVC for a modern card that resists bending and tearing. Frosted, clear, and white options give your brand a sleek, high-tech look that sets it apart.'),

('dual-raised',
 'Dual raised business cards combine two raised finishes on a single card for standout dimension and texture. The layered effect adds depth to your design and gives clients something they will want to keep.'),

('raised-spot-uv',
 'Raised spot UV business cards apply a glossy, raised clear coating to selected areas of your design. The contrast between the raised gloss and the matte background highlights logos and details with striking, tactile emphasis.'),

('foil-worx',
 'Foil Worx business cards showcase bright metallic foil accents in a range of colors and finishes. Use foil to spotlight logos, text, or borders and give your card a polished, premium presence.'),

('endurace-cards',
 'EndurACE business cards are built for durability, with a thick, layered stock and a tough coating that stands up to heavy handling. A rugged, substantial card that communicates strength and permanence.'),

('leaf-cards',
 'Leaf business cards feature rounded, leaf-shaped corners for a soft, distinctive silhouette. The unique die-cut shape adds personality and helps your card stand out in a stack of standard rectangles.'),

('oval-cards',
 'Oval business cards trade sharp corners for smooth, curved edges that feel approachable and modern. The distinctive shape makes your card memorable while keeping a professional, polished look.'),

('fold-over-cards',
 'Fold-over business cards open to reveal double the printable space, giving you room for extra details, a mini brochure, or a memorable message inside. The folded format adds substance and a premium, tent-style presentation.'),

('flyers-and-brochures',
 'Flyers and brochures are a versatile, affordable way to promote products, services, and events. Available in a wide range of sizes and folding options, they are ideal for handouts, mailers, and in-store displays that put your message directly into customers'' hands.'),

('trading-cards',
 'Custom trading cards are pocket-sized keepsakes that fans and customers love to collect. Feature player stats, product details, team rosters, or event promos to create memorable giveaways, rewards, and collectibles.'),

('postcards',
 'Printed on sturdy card stock, postcards are a proven tool for direct mail campaigns, promotions, and staying top of mind with customers. A variety of sizes, stocks, and finishes help your message stand out in the mailbox.'),

('presentation-folders',
 'Presentation folders keep proposals, price sheets, and marketing materials organized and on-brand. Ideal for meetings, conferences, and trade shows, they come in a range of stocks and finishes for a polished, professional handoff.'),

('announcement-cards',
 'Announcement cards are perfect for sharing news that matters, from grand openings and new locations to product launches and special events. Printed on quality card stock, they deliver your message with a personal, memorable touch.'),

('booklets',
 'Booklets are ideal for catalogs, programs, manuals, and lookbooks. With multiple page counts, sizes, and binding options, they organize detailed information into a clean, professional, easy-to-read format.'),

('calendars',
 'Custom calendars keep your brand in front of customers all year long. Great as client gifts and promotional giveaways, they combine day-to-day usefulness with twelve months of brand visibility.'),

('catalogs',
 'Catalogs showcase your full product line in a polished, browsable format. With flexible page counts and binding options, they are built to display detailed listings, photography, and pricing that drive sales.'),

('counter-cards',
 'Counter cards are compact, self-standing displays designed for checkout counters and tabletops. They are a simple, high-impact way to promote offers, new products, and events right at the point of sale.'),

('door-hangers',
 'Door hangers are a targeted, cost-effective way to reach households and hotel guests directly. Printed on durable stock, they offer plenty of room for eye-catching visuals and messaging that lands right at the doorknob.'),

('envelopes',
 'Custom printed envelopes give your mailings a professional, branded look from the moment they arrive. Available in multiple sizes and styles, with options for return addresses, logos, and full-color designs.'),

('event-tickets',
 'Custom event tickets add a professional touch to concerts, fundraisers, and admissions while helping you track attendance. Sequential numbering, perforations, and stubs are available to keep entry organized and secure.'),

('greeting-cards',
 'Custom greeting cards help you connect with customers, clients, and loved ones for holidays, thank-yous, and special occasions. Choose from premium stocks and finishes for a heartfelt, high-quality result.'),

('hang-tags',
 'Hang tags attach essential product details, pricing, and branding directly to your merchandise. Available in a range of shapes, sizes, and stocks, they add a finished, retail-ready look to apparel and goods.'),

('letterheads',
 'Custom letterhead gives your business correspondence a consistent, professional identity. Printed on quality stock, it reinforces your brand on quotes, invoices, and official documents.'),

('magnets',
 'Custom magnets keep your brand visible on refrigerators, filing cabinets, and vehicles long after they are handed out. Durable and full-color, they are ideal for promotions, giveaways, and save-the-date reminders.'),

('menus',
 'Custom menus present your food and drink offerings with clarity and style. Available in a variety of sizes, stocks, and finishes, including durable coatings that stand up to daily use in busy dining rooms.'),

('ncr-forms',
 'NCR carbonless forms make it easy to keep instant copies of invoices, receipts, and work orders. Multi-part sets transfer writing automatically, so you and your customer each keep a record without messy carbon paper.'),

('notepads',
 'Custom notepads put your brand on every desk while giving customers something they will actually use. Printed and glued into tidy tear-away pads, they are a practical, budget-friendly promotional staple.'),

('posters',
 'Posters deliver big, bold messaging that commands attention. Available in a range of sizes and stocks, they are perfect for storefronts, events, and any open wall space that deserves eye-catching, large-format print.'),

('rack-cards',
 'Rack cards are ideal for high-traffic spots like hotel lobbies, visitor centers, and retail counters. Their tall, slim format is perfect for quick pitches promoting services, attractions, and events to people on the go.'),

('sell-sheets',
 'Sell sheets pack the key benefits of a product or service onto a single, easy-to-scan page. Printed on durable stock, they make a powerful leave-behind for sales calls, trade shows, and follow-ups.'),

('social-cards',
 'Social cards make it easy for customers to find and follow your brand online. Share your handles, QR codes, and profiles on a compact card that grows your audience across every platform.'),

('table-tent-cards',
 'Table tent cards are two-sided, self-standing displays that sit right on tables and counters. They ship flat and set up in seconds, making them perfect for featuring specials, promotions, and events where customers are already seated.'),

('tear-off-cards',
 'Tear-off cards feature perforated tabs that let customers take away your contact info, coupon, or offer while the main piece keeps promoting. A clever, high-response format for community boards and counters.'),

('packaging',
 'Custom packaging protects your products while turning every unboxing into a branded experience. Printed on sturdy stock in a variety of box styles and sizes, it is fully customizable to showcase your logo and design.'),

('custom-boxes',
 'Print-and-trim custom boxes are cut and scored to your specifications, letting you create packaging in unique shapes and sizes. Ideal for retail products, gifts, and specialty items that deserve a standout presentation.'),

('header-cards',
 'Header cards give bagged and carded retail products a professional finish. Printed on premium stock, they display your branding and product details right above the merchandise, ready to hang on a peg or shelf.'),

('table-covers',
 'Custom table covers give trade show booths, events, and displays a clean, professional, fully branded look. Printed on durable polyester with vibrant, long-lasting color across the entire surface.'),

('rigid-signs',
 'Rigid signs cover every need from short-term promotions to permanent installations. Available in a range of lightweight and heavy-duty materials, they are built for both indoor and outdoor display.'),

('wall-arts',
 'Custom wall art turns your photos and designs into striking display pieces for offices, homes, and retail spaces. Available in a range of materials and sizes for a gallery-quality finish.'),

('outdoor-banners',
 'Outdoor banners deliver durable, weather-resistant advertising that goes wherever your customers are. Hang them on fences, storefronts, and event spaces for high-visibility branding that holds up to the elements.'),

('indoor-banners',
 'Indoor banners make a bold statement at trade shows, retail displays, and events. Lightweight and vibrant, they are easy to hang and reuse for eye-catching messaging in any interior space.'),

('flags',
 'Custom flags grab attention at storefronts, events, and trade shows. Printed on premium polyester with dye sublimation for rich, lasting color, they are easy to fold, store, and set up with available hardware.'),

('window-graphics',
 'Window graphics and clings transform glass into prime advertising space. Available in clear, opaque, and see-through styles, they are perfect for storefronts, restaurants, and offices.'),

('wall-decals',
 'Wall decals let you add custom graphics, logos, and messaging to almost any smooth surface. Offered in low-tack and high-tack adhesives to suit both temporary and long-term placements.'),

('floor-graphics',
 'Floor graphics turn unused floor space into attention-grabbing advertising. Printed with durable, slip-resistant material, they guide foot traffic and promote offers right where customers are walking.'),

('vehicle-magnets',
 'Vehicle magnets turn your car or truck into mobile advertising you can remove anytime. Durable and weather-resistant, they put your brand and contact info in front of customers everywhere you drive.'),

('banner-stands',
 'Banner stands pair a printed banner with a portable, easy-to-assemble base for instant, professional displays. Ideal for trade shows, lobbies, and events where you need to set up and pack down fast.'),

('displays',
 'From tabletop signage to large fabric tube displays, our display solutions help your brand command attention at any venue. Available in a range of sizes and styles for indoor and outdoor events.'),

('roll-labels',
 'Roll labels deliver full-color branding that sticks to a wide range of surfaces. Perfect for product packaging, seals, and promotions, they are supplied on convenient rolls with a permanent adhesive.'),

('stickers',
 'Custom stickers are a fun, versatile way to brand products, seal packages, and spread your message. Printed on durable material with a permanent adhesive and easy peel-and-stick backing.'),

('bumper-stickers',
 'Bumper stickers are a durable, weather-resistant way to spread your message on the move. Printed on tough vinyl with strong adhesive, they hold up to sun, rain, and the road.'),

('t-shirts',
 'Custom T-shirts spark conversations and build brand awareness wherever they are worn. Great for giveaways, team uniforms, events, and souvenirs, they turn everyone who wears one into a walking billboard for your brand.'),

('tote-bags',
 'Custom tote bags are a practical, eco-friendly promotional item that keeps your brand in view every day. Printed on durable canvas, they are perfect for retail, events, and branded giveaways.'),

('mugs',
 'Custom mugs put your brand in customers'' hands every morning. Available in popular ceramic styles with vibrant, long-lasting full-color printing that stands up to daily use.'),

('buttons',
 'Custom buttons are a fun, affordable way to promote a brand, campaign, or event. Available in a variety of shapes and sizes with low minimums for easy ordering.')

ON CONFLICT (category_slug) DO UPDATE
  SET description = EXCLUDED.description,
      updated_at  = NOW();
